project_id = "cxiloqsmxzyzkhbnwara"

[functions.sitemap]
verify_jwt = false

[functions.ai-chatbot]
verify_jwt = false

[functions.analyze-content]
verify_jwt = true

[functions.analyze-image]
verify_jwt = true
