project_id = "aeazzctapbhojqendxks"

[functions.sitemap]
verify_jwt = false

[functions.ai-chatbot]
verify_jwt = false

[functions.analyze-content]
verify_jwt = true

[functions.analyze-image]
verify_jwt = true

[functions.execute-scheduled-actions]
verify_jwt = true

[functions.get-users]
verify_jwt = true

[functions.reset-user-password]
verify_jwt = true

[functions.get-user-stats]
verify_jwt = true

[functions.invite-user]
verify_jwt = true
